spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xblog?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: colt1911

file:
  save:
    location: D:\\Code\\Vue_SpringBoot_Project\\XBlog\\xblog\\src\\main\\resources\\public\\
  request:
    path: /file/**
    url: http://localhost:8080/file/